spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3307/${MYSQL_DATABASE:academic_integrity_review}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME:air_user}
    password: ${MYSQL_PASSWORD:air_password}